# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb2cb1c115fe122628b83ed02591b6ecf7847b28a32a8a5334bf82d370aa4b4a7c3664790eef580e26373d265aecdd8110968f52b0ed7c8da6c511bfa9994c78

test:
  secret_key_base: 97543d5591ae4cce116275bc1fc4e94a5421aa847d1fb8c271c692264c5c0235c6b5cb05d13929bdcb68a8a086d1032c99913e2d6471990e1d8ca591b2d9dff2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
