# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6749eb31c97dbb7f7a0951ac66b83a1efa27b9985313f6273a7d6627f33f3197ea15672b2fbc51a4f7076fff7d5c55faa71fec02325e69694069b8040e07683f

test:
  secret_key_base: a28e41af28addf37ea4dbe4ab4ec989a0bfd988fae7a7a0e9c0118f2cc71c239830bca165a13965c65f5d54b0cc9459cca027ac5c09e9c71d3748c061fdec4ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
